# Generated by Django 6.0.4 on 2026-04-20 14:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('sender', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('received_at', models.DateTimeField()),
                ('raw_body_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('IT Technical', 'IT Technical'), ('Marketing', 'Marketing'), ('Tax', 'Tax'), ('Others', 'Others'), ('No Action Required', 'No Action Required'), ('Unclassified', 'Unclassified')], max_length=50)),
                ('confidence', models.FloatField()),
                ('method', models.CharField(choices=[('ai', 'AI'), ('rules', 'Rules'), ('manual', 'Manual')], max_length=10)),
                ('reason', models.TextField()),
                ('requires_review', models.BooleanField(default=False)),
                ('corrected_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to=settings.AUTH_USER_MODEL)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='emails.email')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routed_to', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('routed_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.classification')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_logs', to='emails.email')),
            ],
        ),
    ]
